# Generated by Django 2.1.4 on 2020-11-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchName', models.IntegerField(verbose_name='batch')),
                ('bat_term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=6, verbose_name='term')),
                ('bat_year', models.IntegerField(verbose_name='year')),
            ],
            options={
                'verbose_name_plural': 'Batch',
                'db_table': '"tbl_batch"',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='course ID')),
                ('courseCode', models.CharField(max_length=8, unique=True, verbose_name='course Code')),
                ('crs_title', models.CharField(max_length=50, verbose_name='title')),
                ('crs_shortName', models.CharField(max_length=9, unique=True, verbose_name='short Name')),
                ('crs_category', models.CharField(choices=[('major', 'major'), ('core', 'core'), ('science & mathematics', 'science & mathematics'), ('general education', 'general education'), ('optional', 'optional')], max_length=25, verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Course',
                'db_table': '"tbl_course"',
            },
        ),
        migrations.CreateModel(
            name='CourseOffered',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='courseOffer ID')),
                ('ofr_term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=6, verbose_name='term')),
                ('ofr_year', models.IntegerField(verbose_name='year')),
                ('batchName', models.ForeignKey(db_column='batchName', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Batch', verbose_name='batch')),
                ('courseCode', models.ForeignKey(db_column='courseCode', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Course', to_field='courseCode', verbose_name='course')),
            ],
            options={
                'verbose_name_plural': 'CourseOffered',
                'db_table': 'tbl_courseOffered',
            },
        ),
        migrations.CreateModel(
            name='CreateRoutine',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='createRoutine ID')),
                ('batch', models.ForeignKey(db_column='batchName', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Batch', verbose_name='batch')),
                ('courseCode', models.ForeignKey(db_column='courseCode', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Code', to='exam_scheduler.Course', verbose_name='courseCode')),
                ('crs_shortName', models.ForeignKey(db_column='crs_shortName', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Course', verbose_name='crs_shortName')),
            ],
            options={
                'verbose_name': 'CreateRoutine',
                'verbose_name_plural': 'CreateRoutine',
                'db_table': '"tbl_createRoutine"',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Department ID')),
                ('dpt_code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('dpt_name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Department',
                'db_table': '"tbl_department"',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('exm_type', models.CharField(choices=[('Supplymentary', 'Supplymentary'), ('Mid Term', 'Mid Term'), ('Final', 'Final')], max_length=13, verbose_name='type')),
                ('exm_term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], max_length=6, verbose_name='term')),
                ('exm_year', models.IntegerField(verbose_name='year')),
            ],
            options={
                'verbose_name_plural': 'Exam',
                'db_table': 'tbl_exam',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='faculty ID')),
                ('fac_title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=200, verbose_name='title')),
                ('fac_firstName', models.CharField(max_length=20, verbose_name='first Name')),
                ('fac_lastName', models.CharField(max_length=20, verbose_name='last Name')),
                ('fac_shortName', models.CharField(max_length=3, verbose_name='short Name')),
                ('fac_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='gender')),
                ('fac_designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Senior Lecturer', 'Senior Lecturer'), ('Lecturer', 'Lecturer'), ('Head', 'Head'), ('Dean', 'Dean')], max_length=20, verbose_name='designation')),
                ('DepartmentID', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Department', verbose_name='department')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'db_table': 'tbl_faculty',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programCode', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Program Code')),
                ('pro_name', models.CharField(default='B.Sc. Engg. in CSE', max_length=50, verbose_name='name')),
                ('pro_shortForm', models.CharField(default='CSE', max_length=20, verbose_name='short Form')),
                ('pro_type', models.CharField(choices=[('honours', 'honours'), ('masters', 'masters'), ('diploma', 'diploma'), ('PhD', 'PhD')], default='honours', max_length=7, verbose_name='type')),
                ('DepartmentID', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Department', verbose_name='department')),
            ],
            options={
                'verbose_name_plural': 'Program',
                'db_table': 'tbl_program',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomCode', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='room Code')),
                ('rom_capacity', models.IntegerField(verbose_name='capacity')),
                ('rom_floor', models.CharField(max_length=4, verbose_name='floor')),
                ('rom_type', models.CharField(choices=[('LAB', 'LAB'), ('Classroom', 'Classroom'), ('Seminar Hall', 'Seminar Hall'), ('Library', 'Library')], max_length=12, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Room',
                'db_table': 'tbl_room',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='routine ID')),
                ('courseOfferedID', models.ForeignKey(db_column='courseOfferedID', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.CourseOffered', verbose_name='CourseOffered')),
                ('examID', models.ForeignKey(db_column='examID', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Exam', verbose_name='exam')),
                ('roomCode', models.ForeignKey(db_column='roomCode', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routine',
                'db_table': '"tbl_routine"',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=10, verbose_name='section')),
                ('batchID', models.ForeignKey(db_column='batchName', default='1', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Batch', verbose_name='batch')),
            ],
            options={
                'verbose_name_plural': 'Section',
                'db_table': '"tbl_section"',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='timeSlot ID')),
                ('tst_day', models.CharField(blank=True, choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default=None, max_length=9, null=True, verbose_name='day')),
                ('tst_duration', models.CharField(default='10:00AM-12:00PM', max_length=15, verbose_name='duration')),
                ('tst_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Final', 'Final'), ('Mid Term', 'Mid Term'), ('Supplymentary', 'Supplymentary')], max_length=13, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'TimeSlot',
                'db_table': 'tbl_timeSlot',
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='timeSlotID',
            field=models.ForeignKey(db_column='timeSlotID', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.TimeSlot', verbose_name='timeSlot'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='day',
            field=models.ForeignKey(db_column='day', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.TimeSlot', verbose_name='day'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='dpt_code',
            field=models.ForeignKey(db_column='dpt_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Department', verbose_name='dpt_code'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='duration',
            field=models.ForeignKey(db_column='duration', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='exam_scheduler.TimeSlot', verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='fac_shortName',
            field=models.ForeignKey(db_column='fac_shortName', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Faculty', verbose_name='fac_shortName'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='roomCode',
            field=models.ForeignKey(db_column='room', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Room', verbose_name='roomCode'),
        ),
        migrations.AddField(
            model_name='createroutine',
            name='section',
            field=models.ForeignKey(db_column='sectionName', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='exam_scheduler.Section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='facultyID',
            field=models.ForeignKey(db_column='facultyID', default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Faculty', verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='sectionName',
            field=models.ForeignKey(db_column='sectionName', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section_Name', to='exam_scheduler.Section', verbose_name='sectionName'),
        ),
        migrations.AddField(
            model_name='course',
            name='programCode',
            field=models.ForeignKey(db_column='programCode', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='batch',
            name='programCode',
            field=models.ForeignKey(db_column='programCode', default='115', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Program', verbose_name='program'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batchName', 'programCode')},
        ),
    ]
