# Generated by Django 2.1.4 on 2020-12-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
