# Generated by Django 2.1.4 on 2020-11-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0003_remove_routine_examid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffered',
            name='courseCode',
        ),
        migrations.AddField(
            model_name='courseoffered',
            name='courseID',
            field=models.ForeignKey(db_column='courseID', default=None, blank='true', null='true',
                                    on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='routine',
            name='examID',
            field=models.ForeignKey(db_column='examID', default=None,
                                    on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Exam', verbose_name='exam'),
        ),
    ]
