# Generated by Django 2.1.4 on 2021-01-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0003_routine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
