# Generated by Django 2.1.4 on 2020-11-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0004_auto_20201111_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffered',
            name='programID',
            field=models.ForeignKey(blank='true', db_column='programCode', default=None, null='true', on_delete=django.db.models.deletion.CASCADE, to='exam_scheduler.Program', verbose_name='program'),
            preserve_default='true',
        ),
    ]
