# Generated by Django 2.1.4 on 2020-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0005_courseoffered_programid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('dayName', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Day',
                'db_table': 'tbl_day',
            },
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='tst_day',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='tst_duration',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='tst_type',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='endingTime',
            field=models.CharField(default=None, max_length=20, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='startingTime',
            field=models.CharField(default=None, max_length=20, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='program',
            name='pro_type',
            field=models.CharField(choices=[('honours', 'honours'), ('masters', 'masters'), ('diploma', 'diploma'), ('PhD', 'PhD')], default='honours', max_length=10, verbose_name='type'),
        ),
    ]
