# Generated by Django 2.1.4 on 2021-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0006_auto_20210204_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='courseTitle',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='facultyFullName',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
