# Generated by Django 2.1.4 on 2020-12-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0007_auto_20201213_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(default=None, max_length=20, primary_key=True, serialize=False, verbose_name='routine ID')),
                ('term', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')], default=None, max_length=6, verbose_name='terms')),
                ('year', models.IntegerField(default=None, verbose_name='year')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default=None, max_length=12, verbose_name='days')),
                ('batchAndSection', models.CharField(default=None, max_length=8)),
                ('courseName', models.CharField(default=None, max_length=40)),
                ('faculty', models.ForeignKey(db_column='faculty', default=None, on_delete=django.db.models.deletion.PROTECT, to='exam_scheduler.Faculty', verbose_name='faculties')),
                ('program', models.ForeignKey(db_column='programCode', default=None, on_delete=django.db.models.deletion.PROTECT, to='exam_scheduler.Program', verbose_name='programs')),
                ('room', models.ForeignKey(db_column='roomCode', default=None, on_delete=django.db.models.deletion.PROTECT, to='exam_scheduler.Room', verbose_name='room')),
                ('timeSlot', models.ForeignKey(db_column='timeSlot', default=None, on_delete=django.db.models.deletion.PROTECT, to='exam_scheduler.TimeSlot', verbose_name='timeSlot')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routine',
                'db_table': '"tbl_routine"',
            },
        ),
    ]
