# Generated by Django 2.1.4 on 2020-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchName',
            field=models.CharField(max_length=20, verbose_name='batch'),
        ),
    ]
