# Generated by Django 2.1.4 on 2020-11-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0002_auto_20201109_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='examID',
        ),
    ]
